### ISSUE TITLE
Crashes on PS Vita 1000, 3.65

### ISSUE THREAD

**Issue by JRHJ510** [hatoving/gdash-vita#1] opened 2024-01-24 02:01 UTC
Files taken from Geometry Dash 2.205 APK that I ripped from my phone, crashes with error C2-12828-1.
[psp2core-1706061291-0x00001039c7-eboot.bin.psp2dmp.zip](https://github.com/hatoving/gdash-vita/files/14031688/psp2core-1706061291-0x00001039c7-eboot.bin.psp2dmp.zip)

**Comment by hatoving** [comment] 2024-01-24 05:26
Do you have ``libfmodstudio.suprx`` installed?

**Comment by hatoving** [comment] 2024-01-24 09:28
hrrrmmmm
are the files also corrwctly placed?
there should be a apk file in ux0:data/gdash cslled GeometryDash.apk.

**Comment by JRHJ510** [comment] 2024-01-24 09:53
> hrrrmmmm are the files also corrwctly placed? there should be a apk file in ux0:data/gdash cslled GeometryDash.apk.

FMOD Files are correctly placed in ux0:data, GeometryDash.apk is in gdash folder. Could it require a specific game version?

**Comment by Rinnegatamante** [comment] 2024-01-24 11:33
> > hrrrmmmm are the files also corrwctly placed? there should be a apk file in ux0:data/gdash cslled GeometryDash.apk.
> 
> FMOD Files are correctly placed in ux0:data, GeometryDash.apk is in gdash folder. Could it require a specific game version?

FMOD goes in ur0:data, not ux0.

**Comment by JRHJ510** [comment] 2024-01-24 12:00
> > > hrrrmmmm are the files also corrwctly placed? there should be a apk file in ux0:data/gdash cslled GeometryDash.apk.
> > 
> > 
> > FMOD Files are correctly placed in ux0:data, GeometryDash.apk is in gdash folder. Could it require a specific game version?
> 
> FMOD goes in ur0:data, not ux0.

Yep, that fixed it, thanks

**Comment by OrangeClouds** [comment] 2024-01-24 15:46
still got same issue, files are all correctly placed. is the version of gdash needed a specific one?

**Comment by hatoving** [comment] 2024-01-24 16:45
Install the new update from the Releases tab. That should work now.

**Comment by hatoving** [comment] 2024-01-24 16:50
Just realized I misunderstood what you said ._.
As of now, the only version I've tested so far is v2.2.13. Are you getting any error or something?

**Comment by OrangeClouds** [comment] 2024-01-24 18:04
i get the same error as OP (C2-12828-1) i also read the crash log and its a prefetch abort exception error. i also installed the update, to no avail.

**Comment by hatoving** [comment] 2024-01-24 18:39
mrrrmrmm
double check just in case; files ur0:data should be named `libfmodstudio.suprx`, `libc.suprx` and `libfios2.suprx`
there also should be an apk called `GeometryDash.apk` in ux0:data/gdash and `libcocos2dcpp.so` to accompany it

**Comment by ZoiD178** [comment] 2024-01-24 19:55
Hello everyone, I don’t know much about FMOD files, is it normal that the libfmodstudio.suprx, libc.suprx and libfios2.suprx weigh 5 kb?

**Comment by JRHJ510** [comment] 2024-01-24 19:55
> Hello everyone, I don’t know much about FMOD files, is it normal that the libfmodstudio.suprx, libc.suprx and libfios2.suprx weigh 5 kb?

They aren't large, they are basically library files. That size seems about correct.

**Comment by ZoiD178** [comment] 2024-01-24 19:56
ok, thanks

**Comment by OrangeClouds** [comment] 2024-01-24 19:59
> mrrrmrmm double check just in case; files ur0:data should be named `libfmodstudio.suprx`, `libc.suprx` and `libfios2.suprx` there also should be an apk called `GeometryDash.apk` in ux0:data/gdash and `libcocos2dcpp.so` to accompany it

yep, all correct. no clue what the issue is, even reinstalled.

**Comment by ZoiD178** [comment] 2024-01-24 20:11
and one more thing, when extracting FMOD plugins I got a message in red font: “ELF IS CORRUPTED.IT IS AS BAD AS MAI.Or its too” and “Could not properly save self auth:80010002”

**Comment by ZoiD178** [comment] 2024-01-24 20:12
what does this have to do with?

**Comment by OrangeClouds** [comment] 2024-01-24 20:22
oh yeah i got that too, but since it did output the files i imagined it just did that

**Comment by Haasman0** [comment] 2024-01-24 20:41
I got that too, I am on 3.60. I saw an issue in the PSVita-RE-tools github about the same issue
https://github.com/TeamFAPS/PSVita-RE-tools/issues/11
I think the reason it does not work and gives an error is because in the end of "I Am The Hero (3.61+!) [3.68], the (3.61+!) [3.68] means it needs firmware 3.68 or higher to play the game (Or decrypt in the current situation). They said to use reFOOD, but I have it installed and does not work sadly, it gives me that error. So to fix, you may need a higher Firmware.
I would suggest Lichtspear (PCSE01010) since it only needs 3.63 or higher so that it works and decrypts with Enso 3.65 at least.

**Comment by ZoiD178** [comment] 2024-01-24 20:48
thank you very much, this helped me

**Comment by hatoving** [comment] 2024-01-24 20:59
is this resolved? if so then i'll close this for good

**Comment by ZoiD178** [comment] 2024-01-24 21:21
yes it's decided

**Comment by hatoving** [comment] 2024-01-24 22:56
ok dokey then

**Closed by hatoving** 2024-01-24 22:56 UTC
